/**
 * catalog.js  —  GENERATED FILE, DO NOT EDIT BY HAND
 * ------------------------------------------------------------------
 * Generated by scripts/generate-catalog.js from the CSV tables in
 * catalog_data/. To make changes, edit the CSVs (or
 * build_catalog_tables.py) and re-run:  npm run generate
 * ------------------------------------------------------------------
 */

export const DEGREES = {
  "BSc Computer Science": {
    "id": "cs",
    "tagline": "Foundations of software, systems, and computation.",
    "core_year1": [
      {
        "id": "CS101",
        "title": "Introduction to Programming",
        "credits": 4
      },
      {
        "id": "MATH101",
        "title": "Discrete Mathematics",
        "credits": 4
      },
      {
        "id": "CS110",
        "title": "Computer Systems Fundamentals",
        "credits": 4
      },
      {
        "id": "WRIT101",
        "title": "Academic Writing",
        "credits": 3
      }
    ],
    "core_year2": [
      {
        "id": "CS201",
        "title": "Data Structures & Algorithms",
        "credits": 4,
        "prereqs": [
          "CS101"
        ]
      },
      {
        "id": "CS210",
        "title": "Computer Architecture",
        "credits": 4,
        "prereqs": [
          "CS110"
        ]
      },
      {
        "id": "CS220",
        "title": "Databases",
        "credits": 4,
        "prereqs": [
          "CS201"
        ]
      },
      {
        "id": "MATH201",
        "title": "Linear Algebra",
        "credits": 3,
        "prereqs": [
          "MATH101"
        ]
      }
    ],
    "tracks": {
      "Software Engineering": {
        "id": "cs_swe",
        "blurb": "Designing, building, and shipping reliable software at scale.",
        "courses": [
          {
            "id": "CS310",
            "title": "Software Design & Architecture",
            "credits": 4,
            "prereqs": [
              "CS201"
            ]
          },
          {
            "id": "CS320",
            "title": "Distributed Systems",
            "credits": 4,
            "prereqs": [
              "CS210",
              "CS220"
            ]
          },
          {
            "id": "CS330",
            "title": "DevOps & Cloud Deployment",
            "credits": 3,
            "prereqs": [
              "CS320"
            ]
          },
          {
            "id": "CS401_SWE",
            "title": "Capstone: Software Engineering",
            "credits": 5,
            "prereqs": [
              "CS310",
              "CS320"
            ]
          }
        ]
      },
      "Artificial Intelligence": {
        "id": "cs_ai",
        "blurb": "Machine learning, reasoning systems, and intelligent agents.",
        "courses": [
          {
            "id": "CS315",
            "title": "Machine Learning Fundamentals",
            "credits": 4,
            "prereqs": [
              "CS201",
              "MATH201"
            ]
          },
          {
            "id": "CS325",
            "title": "Neural Networks & Deep Learning",
            "credits": 4,
            "prereqs": [
              "CS315"
            ]
          },
          {
            "id": "CS335",
            "title": "Agentic & Multi-Agent Systems",
            "credits": 3,
            "prereqs": [
              "CS325"
            ]
          },
          {
            "id": "CS401_AI",
            "title": "Capstone: Artificial Intelligence",
            "credits": 5,
            "prereqs": [
              "CS315",
              "CS325"
            ]
          }
        ]
      }
    }
  },
  "BSc Data Science": {
    "id": "ds",
    "tagline": "Extracting insight and building models from real-world data.",
    "core_year1": [
      {
        "id": "CS101",
        "title": "Introduction to Programming",
        "credits": 4
      },
      {
        "id": "STAT101",
        "title": "Introduction to Statistics",
        "credits": 4
      },
      {
        "id": "MATH101",
        "title": "Discrete Mathematics",
        "credits": 4
      },
      {
        "id": "WRIT101",
        "title": "Academic Writing",
        "credits": 3
      }
    ],
    "core_year2": [
      {
        "id": "CS201",
        "title": "Data Structures & Algorithms",
        "credits": 4,
        "prereqs": [
          "CS101"
        ]
      },
      {
        "id": "STAT201",
        "title": "Probability & Statistical Inference",
        "credits": 4,
        "prereqs": [
          "STAT101"
        ]
      },
      {
        "id": "DS210",
        "title": "Data Wrangling & ETL",
        "credits": 3,
        "prereqs": [
          "CS101"
        ]
      },
      {
        "id": "MATH201",
        "title": "Linear Algebra",
        "credits": 3,
        "prereqs": [
          "MATH101"
        ]
      }
    ],
    "tracks": {
      "Machine Learning": {
        "id": "ds_ml",
        "blurb": "Predictive modeling, model evaluation, and applied ML.",
        "courses": [
          {
            "id": "DS310",
            "title": "Machine Learning Fundamentals",
            "credits": 4,
            "prereqs": [
              "CS201",
              "STAT201"
            ]
          },
          {
            "id": "DS320",
            "title": "Deep Learning",
            "credits": 4,
            "prereqs": [
              "DS310"
            ]
          },
          {
            "id": "DS330",
            "title": "Model Evaluation & MLOps",
            "credits": 3,
            "prereqs": [
              "DS310"
            ]
          },
          {
            "id": "DS401_ML",
            "title": "Capstone: Machine Learning",
            "credits": 5,
            "prereqs": [
              "DS320",
              "DS330"
            ]
          }
        ]
      },
      "Data Engineering": {
        "id": "ds_de",
        "blurb": "Pipelines, distributed data infrastructure, and scalable systems.",
        "courses": [
          {
            "id": "DS315",
            "title": "Data Pipeline Engineering",
            "credits": 4,
            "prereqs": [
              "DS210"
            ]
          },
          {
            "id": "DS325",
            "title": "Distributed Data Systems",
            "credits": 4,
            "prereqs": [
              "DS315"
            ]
          },
          {
            "id": "DS335",
            "title": "Cloud Data Platforms",
            "credits": 3,
            "prereqs": [
              "DS315"
            ]
          },
          {
            "id": "DS401_DE",
            "title": "Capstone: Data Engineering",
            "credits": 5,
            "prereqs": [
              "DS325",
              "DS335"
            ]
          }
        ]
      }
    }
  },
  "BSc Business Administration": {
    "id": "bus",
    "tagline": "Strategy, operations, and decision-making for modern organizations.",
    "core_year1": [
      {
        "id": "BUS101",
        "title": "Principles of Management",
        "credits": 3
      },
      {
        "id": "ECON101",
        "title": "Microeconomics",
        "credits": 3
      },
      {
        "id": "STAT101",
        "title": "Introduction to Statistics",
        "credits": 4
      },
      {
        "id": "WRIT101",
        "title": "Academic Writing",
        "credits": 3
      }
    ],
    "core_year2": [
      {
        "id": "BUS201",
        "title": "Financial Accounting",
        "credits": 4,
        "prereqs": [
          "BUS101"
        ]
      },
      {
        "id": "ECON201",
        "title": "Macroeconomics",
        "credits": 3,
        "prereqs": [
          "ECON101"
        ]
      },
      {
        "id": "BUS210",
        "title": "Organizational Behavior",
        "credits": 3,
        "prereqs": [
          "BUS101"
        ]
      },
      {
        "id": "STAT201",
        "title": "Business Statistics",
        "credits": 3,
        "prereqs": [
          "STAT101"
        ]
      }
    ],
    "tracks": {
      "Marketing Analytics": {
        "id": "bus_mkt",
        "blurb": "Consumer data, campaign analysis, and growth strategy.",
        "courses": [
          {
            "id": "BUS310",
            "title": "Marketing Fundamentals",
            "credits": 3,
            "prereqs": [
              "BUS101"
            ]
          },
          {
            "id": "BUS320",
            "title": "Consumer Analytics",
            "credits": 4,
            "prereqs": [
              "BUS310",
              "STAT201"
            ]
          },
          {
            "id": "BUS330",
            "title": "Digital & Growth Marketing",
            "credits": 3,
            "prereqs": [
              "BUS310"
            ]
          },
          {
            "id": "BUS401_MKT",
            "title": "Capstone: Marketing Analytics",
            "credits": 5,
            "prereqs": [
              "BUS320",
              "BUS330"
            ]
          }
        ]
      },
      "Finance": {
        "id": "bus_fin",
        "blurb": "Corporate finance, valuation, and investment analysis.",
        "courses": [
          {
            "id": "BUS315",
            "title": "Corporate Finance",
            "credits": 4,
            "prereqs": [
              "BUS201"
            ]
          },
          {
            "id": "BUS325",
            "title": "Investment Analysis",
            "credits": 4,
            "prereqs": [
              "BUS315"
            ]
          },
          {
            "id": "BUS340",
            "title": "Risk & Portfolio Management",
            "credits": 3,
            "prereqs": [
              "BUS315"
            ]
          },
          {
            "id": "BUS401_FIN",
            "title": "Capstone: Finance",
            "credits": 5,
            "prereqs": [
              "BUS325",
              "BUS340"
            ]
          }
        ]
      }
    }
  },
  "BSc Psychology": {
    "id": "psych",
    "tagline": "Understanding mind, behavior, and mental processes.",
    "core_year1": [
      {
        "id": "PSY101",
        "title": "Introduction to Psychology",
        "credits": 4
      },
      {
        "id": "STAT101",
        "title": "Introduction to Statistics",
        "credits": 4
      },
      {
        "id": "BIO101",
        "title": "Introduction to Biology",
        "credits": 3
      },
      {
        "id": "WRIT101",
        "title": "Academic Writing",
        "credits": 3
      }
    ],
    "core_year2": [
      {
        "id": "PSY201",
        "title": "Research Methods in Psychology",
        "credits": 4,
        "prereqs": [
          "PSY101",
          "STAT101"
        ]
      },
      {
        "id": "PSY210",
        "title": "Developmental Psychology",
        "credits": 3,
        "prereqs": [
          "PSY101"
        ]
      },
      {
        "id": "PSY220",
        "title": "Biological Psychology",
        "credits": 3,
        "prereqs": [
          "PSY101",
          "BIO101"
        ]
      },
      {
        "id": "STAT201",
        "title": "Statistical Methods for Behavioral Science",
        "credits": 3,
        "prereqs": [
          "STAT101"
        ]
      }
    ],
    "tracks": {
      "Clinical Psychology": {
        "id": "psych_clin",
        "blurb": "Assessment, therapy foundations, and mental health practice.",
        "courses": [
          {
            "id": "PSY310",
            "title": "Abnormal Psychology",
            "credits": 4,
            "prereqs": [
              "PSY201"
            ]
          },
          {
            "id": "PSY320",
            "title": "Clinical Assessment",
            "credits": 4,
            "prereqs": [
              "PSY310"
            ]
          },
          {
            "id": "PSY330",
            "title": "Foundations of Psychotherapy",
            "credits": 3,
            "prereqs": [
              "PSY310"
            ]
          },
          {
            "id": "PSY401_CLIN",
            "title": "Capstone: Clinical Psychology",
            "credits": 5,
            "prereqs": [
              "PSY320",
              "PSY330"
            ]
          }
        ]
      },
      "Cognitive Science": {
        "id": "psych_cog",
        "blurb": "Perception, memory, and the computational study of mind.",
        "courses": [
          {
            "id": "PSY315",
            "title": "Cognitive Psychology",
            "credits": 4,
            "prereqs": [
              "PSY201"
            ]
          },
          {
            "id": "PSY325",
            "title": "Perception & Attention",
            "credits": 3,
            "prereqs": [
              "PSY315"
            ]
          },
          {
            "id": "PSY335",
            "title": "Computational Models of Cognition",
            "credits": 4,
            "prereqs": [
              "PSY315"
            ]
          },
          {
            "id": "PSY401_COG",
            "title": "Capstone: Cognitive Science",
            "credits": 5,
            "prereqs": [
              "PSY325",
              "PSY335"
            ]
          }
        ]
      }
    }
  },
  "BSc Biology": {
    "id": "bio",
    "tagline": "Life sciences from the molecular level to whole ecosystems.",
    "core_year1": [
      {
        "id": "BIO101",
        "title": "Introduction to Biology",
        "credits": 4
      },
      {
        "id": "CHEM101",
        "title": "General Chemistry",
        "credits": 4
      },
      {
        "id": "STAT101",
        "title": "Introduction to Statistics",
        "credits": 3
      },
      {
        "id": "WRIT101",
        "title": "Academic Writing",
        "credits": 3
      }
    ],
    "core_year2": [
      {
        "id": "BIO201",
        "title": "Genetics",
        "credits": 4,
        "prereqs": [
          "BIO101"
        ]
      },
      {
        "id": "BIO210",
        "title": "Cell Biology",
        "credits": 4,
        "prereqs": [
          "BIO101",
          "CHEM101"
        ]
      },
      {
        "id": "CHEM201",
        "title": "Organic Chemistry",
        "credits": 4,
        "prereqs": [
          "CHEM101"
        ]
      },
      {
        "id": "BIO220",
        "title": "Evolutionary Biology",
        "credits": 3,
        "prereqs": [
          "BIO101"
        ]
      }
    ],
    "tracks": {
      "Molecular Biology": {
        "id": "bio_mol",
        "blurb": "Genetics, biochemistry, and life at the cellular level.",
        "courses": [
          {
            "id": "BIO310",
            "title": "Molecular Biology",
            "credits": 4,
            "prereqs": [
              "BIO201",
              "BIO210"
            ]
          },
          {
            "id": "BIO320",
            "title": "Biochemistry",
            "credits": 4,
            "prereqs": [
              "BIO310",
              "CHEM201"
            ]
          },
          {
            "id": "BIO330",
            "title": "Genomics",
            "credits": 3,
            "prereqs": [
              "BIO310"
            ]
          },
          {
            "id": "BIO401_MOL",
            "title": "Capstone: Molecular Biology",
            "credits": 5,
            "prereqs": [
              "BIO320",
              "BIO330"
            ]
          }
        ]
      },
      "Ecology & Environmental Science": {
        "id": "bio_eco",
        "blurb": "Ecosystems, conservation, and environmental change.",
        "courses": [
          {
            "id": "BIO315",
            "title": "Ecology",
            "credits": 4,
            "prereqs": [
              "BIO220"
            ]
          },
          {
            "id": "BIO325",
            "title": "Conservation Biology",
            "credits": 3,
            "prereqs": [
              "BIO315"
            ]
          },
          {
            "id": "BIO340",
            "title": "Environmental Science & Policy",
            "credits": 3,
            "prereqs": [
              "BIO315"
            ]
          },
          {
            "id": "BIO401_ECO",
            "title": "Capstone: Ecology & Environmental Science",
            "credits": 5,
            "prereqs": [
              "BIO325",
              "BIO340"
            ]
          }
        ]
      }
    }
  }
};

/**
 * Flattened lookup: course_id -> { title, credits, prereqs, degree, track }
 */
export function buildCourseIndex(degrees = DEGREES) {
  const index = {};
  for (const [degreeName, degree] of Object.entries(degrees)) {
    for (const course of degree.core_year1) {
      index[course.id] = { ...course, prereqs: course.prereqs || [], degree: degreeName, track: null, level: "core_year1" };
    }
    for (const course of degree.core_year2) {
      index[course.id] = { ...course, prereqs: course.prereqs || [], degree: degreeName, track: null, level: "core_year2" };
    }
    for (const [trackName, track] of Object.entries(degree.tracks)) {
      for (const course of track.courses) {
        index[course.id] = { ...course, prereqs: course.prereqs || [], degree: degreeName, track: trackName, level: "track" };
      }
    }
  }
  return index;
}

export const COURSE_INDEX = buildCourseIndex();

export function getPathCourses(degreeName, trackName = null) {
  const degree = DEGREES[degreeName];
  if (!degree) return [];
  const path = [...degree.core_year1, ...degree.core_year2];
  if (trackName && degree.tracks[trackName]) {
    path.push(...degree.tracks[trackName].courses);
  }
  return path.map(c => c.id);
}

export function getPathCredits(degreeName, trackName = null) {
  const ids = getPathCourses(degreeName, trackName);
  return ids.reduce((sum, id) => sum + (COURSE_INDEX[id]?.credits || 0), 0);
}
